doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # Defina a versão correta do servidor no arquivo .env ou aqui
        # Para MySQL: server_version: '8.0'
        # Para PostgreSQL: server_version: '13'
        server_version: '16' # Confirme a versão do seu banco de dados

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

        orm:
            auto_generate_proxy_classes: true
            auto_mapping: true

when@prod:
    doctrine:
        dbal:
            server_version: '16' # Certifique-se de usar a versão correta do banco em produção
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
